'use strict';

const { SESClient, SendEmailCommand } = require('@aws-sdk/client-ses');
const cron = require('node-cron');
const {
  computeStats,
  computeFileChangeFrequency,
  computeCommitVelocity
} = require('../api/computations');

/**
 * Generate digest HTML content for the given commits and repos.
 *
 * @param {Array} commits - All commits across repos for the period.
 * @param {Array<{repoId: string, name: string}>} repos - Repository metadata.
 * @param {string} period - 'weekly' or 'monthly'.
 * @param {string} [appUrl=''] - Base URL for links back to the app.
 * @returns {string} HTML string for the digest email.
 */
function generateDigestHtml(commits, repos, period, appUrl = '') {
  const stats = computeStats(commits);
  const fileFreq = computeFileChangeFrequency(commits);
  const velocity = computeCommitVelocity(commits, period === 'weekly' ? 'daily' : 'weekly');

  // Top 5 contributors by commit count
  const authorCounts = {};
  for (const c of commits) {
    authorCounts[c.authorEmail] = (authorCounts[c.authorEmail] || 0) + 1;
  }
  const topContributors = Object.entries(authorCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([email, count]) => ({ email, count }));

  // Top 5 hottest files
  const hottestFiles = fileFreq.files.sort((a, b) => b.frequency - a.frequency).slice(0, 5);

  const periodLabel = period === 'weekly' ? 'Weekly' : 'Monthly';

  const repoLinks = repos
    .map((r) => `<li><a href="${appUrl}/?repoId=${r.repoId}">${r.name}</a></li>`)
    .join('\n');

  const contributorRows = topContributors
    .map(
      (c) =>
        `<tr><td style="padding:4px 8px">${c.email}</td><td style="padding:4px 8px">${c.count}</td></tr>`
    )
    .join('\n');

  const fileRows = hottestFiles
    .map(
      (f) =>
        `<tr><td style="padding:4px 8px">${f.path}</td><td style="padding:4px 8px">${f.frequency}</td></tr>`
    )
    .join('\n');

  const velocitySummary =
    velocity.length > 0 ? velocity.map((v) => `${v.period}: ${v.count}`).join(', ') : 'No activity';

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:16px">
  <h1>GInaTor ${periodLabel} Digest</h1>
  <p>Total commits: <strong>${stats.commitCount}</strong> | Contributors: <strong>${stats.contributorCount}</strong> | Files changed: <strong>${stats.fileCount}</strong></p>

  <h2>Top Contributors</h2>
  <table border="1" cellspacing="0" style="border-collapse:collapse">
    <tr><th style="padding:4px 8px">Author</th><th style="padding:4px 8px">Commits</th></tr>
    ${contributorRows}
  </table>

  <h2>Hottest Files</h2>
  <table border="1" cellspacing="0" style="border-collapse:collapse">
    <tr><th style="padding:4px 8px">File</th><th style="padding:4px 8px">Changes</th></tr>
    ${fileRows}
  </table>

  <h2>Commit Velocity</h2>
  <p>${velocitySummary}</p>

  <h2>Repositories</h2>
  <ul>${repoLinks}</ul>

  <hr>
  <p style="font-size:12px;color:#666">This digest was generated by <a href="${appUrl}">GInaTor</a>.</p>
</body>
</html>`;
}

/**
 * Generate a digest for the given repository IDs and period.
 * Fetches commits from the commit store and computes stats.
 *
 * @param {Array<string>} repoIds - Repository IDs to include.
 * @param {string} period - 'weekly' or 'monthly'.
 * @param {object} deps - Injected dependencies.
 * @param {object} deps.commitStore - CommitStore instance.
 * @param {object} deps.adminService - AdminService instance.
 * @param {string} [deps.appUrl=''] - Base URL for links.
 * @returns {Promise<string>} Generated digest HTML.
 */
async function generateDigest(repoIds, period, deps) {
  const { commitStore, adminService, appUrl = '' } = deps;

  const now = new Date();
  const from = new Date(now);
  if (period === 'weekly') {
    from.setDate(from.getDate() - 7);
  } else {
    from.setMonth(from.getMonth() - 1);
  }

  const allCommits = [];
  const repos = [];

  const repoConfigs = await adminService.listRepoConfigs();
  const repoMap = {};
  for (const rc of repoConfigs) {
    repoMap[rc.repoId] = rc;
  }

  for (const repoId of repoIds) {
    const commits = await commitStore.getCommitsByDateRange(
      repoId,
      from.toISOString(),
      now.toISOString()
    );
    allCommits.push(...commits);
    const rc = repoMap[repoId];
    repos.push({ repoId, name: rc ? rc.name : repoId });
  }

  return generateDigestHtml(allCommits, repos, period, appUrl);
}

/**
 * Send digest email to a list of users via SES.
 * Logs failures per user without interrupting others.
 *
 * @param {Array<string>} userEmails - Email addresses to send to.
 * @param {string} digestHtml - HTML content of the digest.
 * @param {object} [options]
 * @param {string} [options.fromEmail='noreply@ginator.app'] - Sender email.
 * @param {string} [options.subject] - Email subject.
 * @param {object} [options.sesClient] - Injected SES client (for testing).
 * @param {object} [options.logger=console] - Logger instance.
 * @returns {Promise<{sent: number, failed: number, errors: Array<{email: string, error: string}>}>}
 */
async function sendDigest(userEmails, digestHtml, options = {}) {
  const {
    fromEmail = 'noreply@ginator.app',
    subject = 'GInaTor Digest',
    logger = console
  } = options;

  const sesClient =
    options.sesClient ||
    new SESClient({
      region: process.env.AWS_REGION || 'us-east-1'
    });

  let sent = 0;
  let failed = 0;
  const errors = [];

  for (const email of userEmails) {
    try {
      await sesClient.send(
        new SendEmailCommand({
          Source: fromEmail,
          Destination: { ToAddresses: [email] },
          Message: {
            Subject: { Data: subject },
            Body: { Html: { Data: digestHtml } }
          }
        })
      );
      sent++;
    } catch (err) {
      failed++;
      errors.push({ email, error: err.message });
      logger.error(`Failed to send digest to ${email}: ${err.message}`);
    }
  }

  return { sent, failed, errors };
}

/**
 * Schedule the digest email cron job.
 *
 * @param {object} deps - Injected dependencies.
 * @param {object} deps.adminService - AdminService instance.
 * @param {object} deps.commitStore - CommitStore instance.
 * @param {string} [deps.appUrl=''] - Base URL for links.
 * @param {object} [deps.sesClient] - Injected SES client.
 * @param {object} [deps.logger=console] - Logger instance.
 * @returns {object|null} The cron task, or null if digest is disabled.
 */
async function scheduleDigest(deps) {
  const { adminService, logger = console } = deps;

  const enabled = await adminService._getSetting('digestEnabled');
  if (enabled !== 'true') {
    logger.info('Digest email is disabled.');
    return null;
  }

  const frequency = (await adminService._getSetting('digestFrequency')) || 'weekly';
  const repoIdsRaw = await adminService._getSetting('digestRepoIds');
  const repoIds = repoIdsRaw ? JSON.parse(repoIdsRaw) : [];

  if (repoIds.length === 0) {
    logger.info('No repositories configured for digest.');
    return null;
  }

  // Weekly: Monday 9am UTC, Monthly: 1st of month 9am UTC
  const cronExpr = frequency === 'monthly' ? '0 9 1 * *' : '0 9 * * 1';

  const task = cron.schedule(cronExpr, async () => {
    try {
      logger.info(`Running ${frequency} digest...`);

      const digestHtml = await generateDigest(repoIds, frequency, deps);

      // Get approved users who haven't opted out
      const allUsers = await adminService.docClient.send(
        new (require('@aws-sdk/lib-dynamodb').ScanCommand)({
          TableName: 'Users',
          FilterExpression: '#s = :approved',
          ExpressionAttributeNames: { '#s': 'status' },
          ExpressionAttributeValues: { ':approved': 'approved' }
        })
      );

      const userEmails = (allUsers.Items || []).filter((u) => !u.digestOptOut).map((u) => u.email);

      if (userEmails.length === 0) {
        logger.info('No eligible users for digest.');
        return;
      }

      const result = await sendDigest(userEmails, digestHtml, {
        sesClient: deps.sesClient,
        logger
      });

      logger.info(`Digest sent: ${result.sent} succeeded, ${result.failed} failed.`);
    } catch (err) {
      logger.error(`Digest job failed: ${err.message}`);
    }
  });

  logger.info(`Digest scheduled: ${frequency} (cron: ${cronExpr})`);
  return task;
}

module.exports = {
  generateDigest,
  generateDigestHtml,
  sendDigest,
  scheduleDigest
};
